/**
 * Test script to send an email via the Shared Email API Worker
 * 
 * Usage:
 * 1. Make sure your worker is running locally (npm run start)
 * 2. Run this script: npx tsx scripts/test-email.ts
 * 
 * Note: You can override the API URL or API Key by setting environment variables:
 * API_URL=https://your-production-worker.workers.dev API_KEY=your_secret_key npx tsx scripts/test-email.ts
 */

const API_URL = process.env.API_URL || 'https://shared-email-api.dark-mode-d021.workers.dev';
const API_KEY = process.env.API_KEY || 'development_secret_key'; // Replace with your Dev/Prod API Key

async function sendTestEmail() {
  const payload = {
    to: 'gokul@rareminds.in',
    subject: 'Test Email Delivery - Shared Email API',
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; color: #333;">
        <h2 style="color: #0056b3;">Shared Email API Worker Tests</h2>
        <p>Hi Gokul,</p>
        <p>This is a test email generated by the new highly-available Cloudflare <strong>Shared Email API</strong>.</p>
        <div style="background-color: #f8f9fa; padding: 15px; border-left: 4px solid #0056b3; margin-top: 20px;">
          <strong>System Status:</strong>
          <ul>
            <li>✨ O(N²) Memory leaks patched</li>
            <li>🚀 Rate Limiting isolated</li>
            <li>🔒 Secure routing strictly enforced</li>
          </ul>
        </div>
        <p style="margin-top: 30px; font-size: 12px; color: #777;">
          Sent by Cloudflare Workers via AWS SES.
        </p>
      </div>
    `,
    text: 'Hi Gokul, this is a test email from the Shared Email API Worker validating that plain-text fallbacks work.',
  };

  console.log(`Sending email to ${payload.to} via ${API_URL}/send...`);

  try {
    const response = await fetch(`${API_URL}/send`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Internal-Api-Key': API_KEY, // Or Authorization: Bearer <key>
      },
      body: JSON.stringify(payload),
    });

    const data = await response.json();

    if (response.ok) {
      console.log('✅ Email sent successfully!');
      console.log('Message ID:', data.messageId);
    } else {
      console.error('❌ Failed to send email.');
      console.error('Status:', response.status);
      console.error('Error Details:', JSON.stringify(data, null, 2));
    }
  } catch (error) {
    console.error('❌ Network error during request:', error);
  }
}

sendTestEmail();
